"""
The Rivhit "new items" import format, reverse-engineered from a real file
dad has been maintaining by hand (tests/fixtures/sample_rivhit_new_items_ss24.xls).

It's a legacy .xls file with NO header row, one row per SKU (item + size +
color), and exactly 11 columns:

  A  rivhit_item_number  running integer, strictly sequential with zero
                          gaps across the whole multi-season file (observed
                          4713..8885, one per row, no repeats/skips). This
                          is a manually-assigned catalog number that must
                          continue from wherever the last file left off -
                          it is NOT auto-generated by Rivhit on import.
  B  description          free text: "{Item Description}, {Size}, {Color
                          Description}, Item {manufacturer item code}"
                          e.g. "Bomber Jacket, S, Slate Brown, Item 35101.240078"
                          Color Description may be empty (", , Item ...").
  C  barcode               manufacturer barcode (EAN-13), as a plain string.
  D-J (7 columns)          always blank in every observed row. Meaning
                          unknown - preserved as blank in output, matching
                          the established convention.
  K  price                 a single numeric price per row. Which source
                          price field this corresponds to (retail vs.
                          wholesale/cost, and in which currency) is not
                          yet confirmed - see docs/rivhit_format_notes.md.

One junk/note row was found in the sample (a comment embedded as a row
instead of real product data) - parsing tolerates but flags this rather
than silently dropping it, since dad may want to review such rows by hand.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from .source_parser import ProductRow

_NUM_COLUMNS = 11
_BLANK_COLUMNS = tuple(range(3, 10))  # D..J, 0-indexed columns 3-9

# Matches "<description>, <size>, <color description>, Item <mfg item code>"
# where color description may be empty.
_DESCRIPTION_PATTERN = re.compile(r"^(?P<description>.*), (?P<size>[^,]+), (?P<color>[^,]*), Item (?P<item_code>\S+)\s*$")


@dataclass(frozen=True)
class RivhitRow:
    rivhit_item_number: int
    description: str
    size: str
    color_description: str
    manufacturer_item_code: str
    barcode: str | None
    price: float | None
    row_index: int  # 0-based row in the source file, for error messages
    is_valid: bool  # False if the description didn't match the expected pattern
    raw_description: str

    @property
    def sku_key(self) -> str:
        return f"{self.manufacturer_item_code}-{self.color_description}-{self.size}"


def _clean_barcode(value: object) -> str | None:
    if value is None or value == "":
        return None
    if isinstance(value, float):
        # xlrd/openpyxl read numeric-looking barcodes as floats (e.g. 8715738826175.0).
        return str(int(value))
    return str(value).strip() or None


def parse_rivhit_new_items_file(path: str | Path) -> list[RivhitRow]:
    """Parse an existing Rivhit "new items" .xls/.xlsx file for inspection/testing.

    Returns one RivhitRow per data row (no header row expected). Rows whose
    description doesn't match the expected pattern are still returned, with
    is_valid=False, rather than silently dropped.
    """
    path = Path(path)
    if path.suffix.lower() == ".xls":
        rows_raw = _read_xls(path)
    else:
        rows_raw = _read_xlsx(path)

    results: list[RivhitRow] = []
    for row_idx, values in enumerate(rows_raw):
        if len(values) < _NUM_COLUMNS:
            values = list(values) + [None] * (_NUM_COLUMNS - len(values))

        raw_id = values[0]
        try:
            rivhit_item_number = int(raw_id)
        except (TypeError, ValueError):
            rivhit_item_number = -1

        raw_description = "" if values[1] is None else str(values[1])
        barcode = _clean_barcode(values[2])
        price = values[10] if isinstance(values[10], (int, float)) else None

        match = _DESCRIPTION_PATTERN.match(raw_description)
        if match:
            results.append(
                RivhitRow(
                    rivhit_item_number=rivhit_item_number,
                    description=match.group("description"),
                    size=match.group("size"),
                    color_description=match.group("color"),
                    manufacturer_item_code=match.group("item_code"),
                    barcode=barcode,
                    price=price,
                    row_index=row_idx,
                    is_valid=True,
                    raw_description=raw_description,
                )
            )
        else:
            results.append(
                RivhitRow(
                    rivhit_item_number=rivhit_item_number,
                    description=raw_description,
                    size="",
                    color_description="",
                    manufacturer_item_code="",
                    barcode=barcode,
                    price=price,
                    row_index=row_idx,
                    is_valid=False,
                    raw_description=raw_description,
                )
            )
    return results


def _read_xls(path: Path) -> list[list[object]]:
    import xlrd

    wb = xlrd.open_workbook(str(path))
    sheet = wb.sheet_by_index(0)
    return [[sheet.cell_value(r, c) for c in range(sheet.ncols)] for r in range(sheet.nrows)]


def _read_xlsx(path: Path) -> list[list[object]]:
    import openpyxl

    wb = openpyxl.load_workbook(path, data_only=True)
    sheet = wb.worksheets[0]
    return [[cell.value for cell in row] for row in sheet.iter_rows()]


def find_id_gaps(rows: list[RivhitRow]) -> list[tuple[int, int]]:
    """Return (previous_id, next_id) pairs wherever the running ID sequence
    isn't consecutive, so a caller can sanity-check a file before trusting it
    as the source of the "next available ID"."""
    ids = [r.rivhit_item_number for r in rows if r.rivhit_item_number >= 0]
    return [(ids[i], ids[i + 1]) for i in range(len(ids) - 1) if ids[i + 1] - ids[i] != 1]


def next_available_id(rows: list[RivhitRow]) -> int | None:
    """The next running ID to use, based on the highest ID seen in an existing file."""
    ids = [r.rivhit_item_number for r in rows if r.rivhit_item_number >= 0]
    return max(ids) + 1 if ids else None


def format_description(product: ProductRow) -> str:
    """Build the Rivhit description string for a product row, matching the
    exact format observed in dad's existing files:
    "{Item Description}, {Size}, {Color Description}, Item {manufacturer item code}"
    """
    color = product.color_description or ""
    size = product.size or ""
    return f"{product.description}, {size}, {color}, Item {product.item_code}"


def build_rivhit_rows(
    products: list[ProductRow],
    start_id: int,
    price_field: str = "wholesale_price",
) -> list[RivhitRow]:
    """Build RivhitRow records ready to write out, assigning sequential IDs
    starting at start_id (use next_available_id() on dad's last export to
    compute this) and pulling the price from the given ProductRow field.
    """
    if price_field not in ("wholesale_price", "retail_price"):
        raise ValueError(f"Unsupported price_field: {price_field!r}")

    rows: list[RivhitRow] = []
    for offset, product in enumerate(products):
        price = getattr(product, price_field)
        rows.append(
            RivhitRow(
                rivhit_item_number=start_id + offset,
                description=product.description,
                size=product.size or "",
                color_description=product.color_description or "",
                manufacturer_item_code=product.item_code,
                barcode=product.barcode,
                price=price,
                row_index=offset,
                is_valid=True,
                raw_description=format_description(product),
            )
        )
    return rows


def write_rivhit_xls(rows: list[RivhitRow], path: str | Path) -> None:
    """Write rows out in the exact legacy .xls layout dad's existing files use:
    A=running id, B=description, C=barcode, D-J=blank, K=price."""
    import xlwt

    wb = xlwt.Workbook()
    sheet = wb.add_sheet("new items")
    for row_idx, row in enumerate(rows):
        sheet.write(row_idx, 0, row.rivhit_item_number)
        sheet.write(row_idx, 1, row.raw_description)
        sheet.write(row_idx, 2, row.barcode or "")
        for col in _BLANK_COLUMNS:
            sheet.write(row_idx, col, "")
        sheet.write(row_idx, 10, row.price if row.price is not None else 0)
    wb.save(str(path))
